---
UDF_CLUSTER_HOST: buffer-metrics.cgbexruym8z7.us-east-1.redshift.amazonaws.com
UDF_CLUSTER_PORT: 5439
UDF_CLUSTER_DB_NAME: buffermetrics
UDF_CLUSTER_USER: buffer
UDF_CLUSTER_PASSWORD: jqEwNiPffM2HpsuDqexXBRxKi8kt
